* Introdução
Este é o =jclmntn_emacs=, um arquivo org-mode que contém minha configuração de Emacs em formato literário (/ou seria letrado?/). Algumas das minhas decisões e lembretes do porquê ter feito algumas coisas estão aqui. Não se esqueça de executar =C-c C-v t= depois de modificar esse arquivo.

* Coisas para fazer
Vou deixar aqui algumas coisas que eu gostaria de melhorar e que pretendo ajustar com o passar do tempo
** TODO Corrigir o cookie de completions
:LOGBOOK:
- State "TODO"       from              [2026-09-01 Tue 18:14]
:END:
** TODO Melhorar as completions de portugues
:LOGBOOK:
- Note taken on [2026-09-02 Wed 16:32] \\
  por exemplo, seria possível adicionar completion preview assim:
  #+begin_src elisp
  ;; Set cape-dict to use your Portuguese words file
  (use-package cape
    :custom
    (cape-dict-file (expand-file-name "pt_BR_words.txt" user-emacs-directory)))

  ;; Add cape-dict locally to Org mode without destroying other CAPFs
  (defun jclmntn/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode)
    (add-hook 'completion-at-point-functions #'cape-dict nil t)
    (add-hook 'completion-at-point-functions 
              (cape-capf-super #'yasnippet-capf) nil t))
  #+end_src
- Note taken on [2026-09-02 Wed 16:26] \\
  O aspell tem umas completions meio nada a ver, com vários caracteres sobrando.
- State "TODO"       from              [2026-09-02 Wed 16:26]
:END:
** TODO Fazer com que as completions do org-mode tenham preview
:LOGBOOK:
- State "TODO"       from              [2026-09-02 Wed 16:27]
:END:
** TODO Fazer com que completions apareçam abaixo do minibuffer
:LOGBOOK:
- State "TODO"       from              [2026-09-01 Tue 18:14]
:END:
** DONE Corrigir o problema de completions no org-mode, que não insere cabeçalhos
CLOSED: [2026-09-02 Wed 18:56]
:LOGBOOK:
- Note taken on [2026-09-02 Wed 18:56] \\
Causa raiz encontrada: o problema não era do org-mode nem do evil. Algumas funções de completion (ex: =pcomplete-completions-at-point=, usado pelo org para completar =[[*heading]]=) chamam =exit-minibuffer= mesmo quando não há um minibuffer de verdade ativo (situação de =completion-in-region=, como ao completar texto direto no buffer).  Isso gera o erro "(no-catch exit nil)", porque =exit-minibuffer= só funciona dentro de uma sessão real de minibuffer. Corrigido interceptando =exit-minibuffer= com uma advice: se não estivermos de fato num minibuffer (=(not (minibufferp))=), redireciona para =choose-completion= (o comando certo para esse caso) em vez de deixar o erro estourar. Ver bloco =(use-package minibuffer ...)=, dentro do =:config=.
- State "DONE"       from "TODO"       [2026-09-02 Wed 18:56]
- Note taken on [2026-09-02 Wed 16:49] \\
  O problema é mais cabeludo do que isso, parece que a função que insere coisas do completion está funcionando incorretamente. A solução candidata:
  #+begin_src elisp
  (with-eval-after-load 'completion-list
    (define-key completion-list-mode-map (kbd "RET") #'choose-completion))
  #+end_src
- Note taken on [2026-09-01 Tue 18:15] \\
  É um problema chatinho, que eu não sei o que faz acontecer, mas suspeito que tenha a ver com o evil-mode.
- State "TODO"       from              [2026-09-01 Tue 18:15]
:END:
** DONE Corrigir o espaçamento entre colunas no =consult=
CLOSED: [2026-09-02 Wed 16:34]
:LOGBOOK:
- Note taken on [2026-09-02 Wed 16:34] \\
  Parece que foi resolvido diminuindo a quantidade de caracteres. Preciso pensar noutros casos que faziam isso surgir.
- State "DONE"       from "TODO"       [2026-09-02 Wed 16:34]
- Note taken on [2026-09-01 Tue 19:35] \\
  Sugestões advindas do =consult= que preenchem o =Completions= buffer estão com um espaçamento muito grande.
- State "TODO"       from              [2026-09-01 Tue 19:35]
:END:
** TODO Ajustar o surgimento de buffers de captura
:LOGBOOK:
- State "TODO"       from              [2026-09-01 Tue 20:22]
- Note taken on [2026-09-01 Tue 20:22] \\
  Quando faço uma captura, o buffer de captura aberto esconde o que estava previamente sendo feito. Seria mais elegante se ele só abrisse algo, sem fechar o buffer.
:END:
* Configurações gerais
Aqui vai todo o comboio de coisas que não são necessariamente relacionadas aos temas abaixo, mas estão por aqui. Localização de variáveis customizadas, backups, numeração global, numeração relativa, remoção de tabs por espaços e tantas outras coisa.
#+begin_src elisp :tangle "init.el"
;; -*- lexical-binding: t; -*-
(use-package emacs
  :custom
  ((custom-file "~/.emacs.d/emacs-custom.el")               ;; Define a localização do arquivo com opções customizadas
   (backup-directory-alist '(("." . "~/.emacs.d/backup/"))) ;; Define a localização dos backups
   (global-display-line-numbers-mode t)                     ;; Ativa a numeração global
   (display-line-numbers-type 'visual)                      ;; Ativa a numeração relativa
   (indent-tabs-mode nil)                                   ;; Good riddance, Tabs
   (tab-width 4) ;;Tab = 4 espaços
   (xref-search-program 'ripgrep)
   (tab-always-indent 'complete)
   (inhibit-startup-message t)
   (ring-bell-function #'ignore)
   (ansi-color-for-compilation-mode t))
  :config
  ;; Adiciona o MELPA à lista de pacotes possíveis
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  ;; Para não poluir a configuração com ensures desnecessários
  (require 'use-package-ensure)
  (setq use-package-always-ensure t)
  ;; Inicia o Emacs com tela cheia
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
  ;; Carrega arquivo de configurações
  (load custom-file)
  (dolist (mode '(eshell-mode-hook dired-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
  ;; Ajustes de codificação quando estiver usando Windows
  (pcase system-type
    (windows-nt
     (prefer-coding-system 'utf-8)
     (set-default-coding-systems 'utf-8)
     (set-terminal-coding-system 'utf-8)
     (set-keyboard-coding-system 'utf-8)
     (setq-default default-process-coding-system '(utf-8 . cp1252))
     ;; Tooling no Windows
     (dolist (path '("C:/Users/jose/Portable/msys64/usr/bin/"
                     "C:/Users/jose/Portable/fd"
                     "C:/Users/jose/Portable/rg"
                     "~/Portable/Git/bin"
                     "~/Repos"))
       (add-to-list 'exec-path (expand-file-name path)))
     (setenv "PATH" (mapconcat #'identity exec-path path-separator))))
  ;; Configurações de cores no compile-mode
  (add-hook 'compilation-filter-hook #'ansi-color-compilation-filter))
#+end_src
** Fazendo com que links no emacs abram o navegador no windows         :WSL:
Achei isso por aí.
#+begin_src elisp :tangle "init.el"
(setq-default sysTypeSpecific  system-type)
(cond 
;; If type is "gnu/linux", override to "wsl/linux" if it's WSL.
((eq sysTypeSpecific 'gnu/linux)  
(when (string-match "Linux.*Microsoft.*Linux" 
                    (shell-command-to-string "uname -a"))

    (setq-default sysTypeSpecific "wsl/linux") ;; for later use.
    (setq
    cmdExeBin"/mnt/c/Windows/System32/cmd.exe"
    cmdExeArgs '("/c" "start" "") )
    (setq
    browse-url-generic-program  cmdExeBin
    browse-url-generic-args     cmdExeArgs
    browse-url-browser-function 'browse-url-generic)
    )))
#+end_src
* Configurações de Navegação e Comandos
** Favoritos
#+begin_src elisp :tangle "init.el"
(use-package bookmark
  :config
  (bookmark-store "Configurações" `((filename . ,(expand-file-name "~/.emacs.d/jclmntn_emacs.org")) (position . 1)) nil)
  (bookmark-store "Repositórios" `((filename . ,(expand-file-name "~/Repos/")) (position . 1)) nil)
  (bookmark-save))
#+end_src
#+end_src
** Leader Keys
Hoje, a minha escolha para configurar comandos e navegação com leader-keys é 100% baseada no =general.el=, não sei se isso vai mudar um dia.
#+begin_src elisp :tangle "init.el"
(use-package general
  :config
  (general-create-definer jclmntn/leader-keys
                          :keymaps '(normal insert visual emacs)
                          :prefix "SPC"
                          :global-prefix "C-SPC"))

(jclmntn/leader-keys
  ;; "d"   '(dbtel-menu :which-key)
  "s"   '(jclmntn/toggle-speedbar-window :which-key)
  "ca"  '(eglot-code-actions :which-key)
  "cr"  '(eglot-rename :which-key)
  "cf"  '(eglot-format :which-key)
  "RET" '(consult-bookmark :which-key)
  "/"   '(consult-ripgrep :which-key)
  "."   '(consult-fd :which-key)
  "i"   '(consult-imenu :which-key)
  "f"   '(consult-flymake :which-key)
  "oc"  '(org-capture :which-key)
  "oa"  '(org-agenda :which-key)
  "nn"  '(denote :which-key)
  "nr"  '(denote-rename-file :which-key)
  "nl"  '(denote-link :which-key)
  "nj"  '(denote-journal-new-or-existing-entry :which-key)
  "nsl" '(denote-sequence-link :which-key)
  "nsf" '(denote-sequence-find :which-key)
  "nss" '(denote-sequence :which-key)
  "nf"  '(consult-notes :which-key)
  "nb"  '(denote-backlinks :which-key)
  "nwo" '(citar-open :which-key)
  "nwc" '(citar-create-note :which-key)
  "nwx" '(citar-denote-nocite :which-key))
#+end_src
** Todas As Coisas Más (evil)
Nesta seção, eu lido com todas as minhas configurações do =evil=, a camada de =vi= extensível para o Emacs.
*** O evil-mode em si                                              :WSL:
Sem grandes detalhes, exceto pela questão das marcas. Criei uma função denominada =jclmntn/my-bind-layout-marks= que é uma função utilitária para configurar marcas usando o Emacs principalmente considerando o fato de que eu utilizo o layout internacional com dead-keys no Fedora/WSL. Utilizar dead-keys faz com que certas marcas não funcionem, até porque quando pressiono "'" no meu teclado, embora apareça um caractere, não acontece nada de verdade nos buffers, porque o sistema (X11) está esperando pelo próximo caractere.
#+begin_src elisp :tangle "init.el"
(defun jclmntn/my-bind-layout-marks (alist evil-fn prefix)
  (dolist (item alist)
    (let* ((key (car item))
           (val (cdr item))
           (sym-name (format "my-layout-%s-%c" prefix val))
           (sym (intern sym-name)))
      (defalias sym `(lambda ()
                      (interactive)
                      (funcall ',evil-fn ,val)))
      (define-key evil-normal-state-map (kbd key) sym))))
#+end_src

Nessa parte, aquela função maluca é utilizada: para cada caractere especial devido ao layout internacional, eu aplico a função de modo que as marcas fiquem disponíveis novamente. Tenho minha dúvida de que esse trabalho seja útil, até porque as marcas nem são features que eu utilizo de verdade no Vim/Emacs.
#+begin_src elisp :tangle "init.el"
(use-package evil
  :init
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)
  (setq evil-want-C-i-jump t)
  :hook
  ;; Preciso fazer isso pra corrigir o problema de completion.
  (completion-in-region-mode . evil-normalize-keymaps)
  :config
  (evil-mode 1)
  (evil-global-set-key 'motion "j" 'evil-next-visual-line)
  (evil-global-set-key 'motion "k" 'evil-previous-visual-line)
  (evil-set-undo-system 'undo-redo)
  ;; No emacs 31, o minibuffer fica doidão!! Candidato a PR.
  (evil-set-initial-state 'minibuffer-mode 'emacs)
  (evil-set-initial-state 'completion-list-mode 'emacs)
  (evil-make-overriding-map completion-in-region-mode-map)
  (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)
  (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
  (define-key evil-normal-state-map (kbd "C-.") nil)
  (define-key evil-normal-state-map (kbd "M-.") nil)
  (setq alist-mark-set '(("À" . ?A) ("È" . ?E) ("Ì" . ?I) ("Ò" . ?O) ("Ù" . ?U) ("à" . ?a)
                         ("è" . ?e) ("ò" . ?o) ("ù" . ?u) ("Ǘ" . ?V) ("ǘ" . ?v) ("?" . ?N)
                         ("?" . ?n) ("?" . ?W) ("?" . ?w) ("?" . ?Y) ("?" . ?y)))
  (setq alist-line-set '(("Á" . ?A) ("É" . ?E) ("Í" . ?I) ("Ó" . ?O) ("Ú" . ?U) ("Ý" . ?y)
                         ("á" . ?a) ("é" . ?e) ("í" . ?i) ("ó" . ?o) ("ú" . ?u) ("ý" . ?y)
                         ("N" . ?N) ("n" . ?n) ("Ǘ" . ?V) ("ǘ" . ?v) ("Ẃ" . ?W) ("ẃ" . ?w)))
  (setq alist-reg-set '(("Ä" . ?A) ("Ë" . ?E) ("Ï" . ?O) ("Ö" . ?U) ("Ü" . ?U) ("ä" . ?a)
                        ("ë" . ?e) ("ï" . ?i) ("ö" . ?o) ("ü" . ?u) ("ÿ" . ?y) ("Ÿ" . ?Y)
                        ("Ḧ" . ?H) ("ḧ" . ?h) ("Ẅ" . ?W) ("ẅ" . ?w) ("ẗ" . ?t)))
  (jclmntn/my-bind-layout-marks alist-mark-set #'evil-goto-mark "mark")
  (jclmntn/my-bind-layout-marks alist-line-set #'evil-goto-line "line")
  (jclmntn/my-bind-layout-marks alist-reg-set #'evil-use-register "reg"))
#+end_src
*** Extensões para o evil
Eu utilizo algumas extensões do evil. Às vezes uso =evil-collection=, às vezes uso =evil-surround=. Admito que poderia usar esse último com mais frequência. Adicionei recentemente algumas keybindings para o =minibuffer=, vamos ver se vai dar certo.
#+begin_src elisp :tangle "init.el"
(use-package evil-collection
  :after evil
  :config
  (evil-collection-init)
  (evil-collection-eshell-setup)
  (evil-collection-eat-setup))

;; (with-eval-after-load 'evil-collection
;;   (evil-collection-define-key 'normal 'minibuffer-local-map
;;     (kbd "<escape>") 'abort-minibuffers
;;     (kbd "gg")       'minibuffer-beginning-of-buffer
;;     (kbd "j")        'next-line-or-history-element
;;     (kbd "k")        'previous-line-or-history-element
;;     (kbd "gj")       'next-matching-history-element
;;     (kbd "gk")       'previous-matching-history-element
;;     (kbd "C-u")      'minibuffer-complete-history
;;     (kbd "C-d")      'minibuffer-complete-defaults)

;;   (evil-collection-define-key 'insert 'minibuffer-local-map
;;     (kbd "C-n")      'next-line-or-history-element
;;     (kbd "C-p")      'previous-line-or-history-element))

(use-package evil-surround
  :after evil
  :ensure t
  :config
  (global-evil-surround-mode 1))
#+end_src

* Pacotes isolados
Aqui vão os pacotes que estão sem categoria clara, ao menos no momento da escrita desse documento.
** ediff
Aqui eu uso uma definição para o =ediff= que torna ele um pouco menos assustador. Me inspirei no [[https:protesilaos.com]].
#+begin_src elisp :tangle "init.el"
  (use-package ediff
    :ensure nil
    :custom
    ((ediff-split-window-function 'split-window-horizontally)
     (ediff-window-setup-function 'ediff-setup-windows-plain)))
#+end_src
** dired
Com as configurações a seguir, eu garanto que múltiplos buffers do =dired= não ficam espalhados entre sessões. Além disso, quando tenho dois buffers do =dired= abertos e eu uso =dired-rename-file=, ele entende que quero mover ou copiar o arquivo de um diretório para o outro.
#+begin_src elisp :tangle "init.el"
(use-package dired
  :ensure nil
  :custom
  ((dired-kill-when-opening-new-dired-buffer t)
   (dired-dwim-target t)))
#+end_src
** vundo
Para ter uma árvore de refazer/desfazer, eu utilizo o =vundo=.
#+begin_src elisp :tangle "init.el"
(use-package vundo)
#+end_src
** wgrep
#+begin_src elisp :tangle "init.el"
(use-package wgrep)
#+end_src
** speedbar
No Emacs 31, o =speedbar= se torna usável com a possibilidade de utilizá-lo em janelas.
#+begin_src elisp :tangle "init.el"
  (use-package speedbar
    :ensure nil
    :custom ((speedbar-prefer-window t)
             (speedbar-window-dedicated-window t)))
#+end_src

Criei uma função dedicada para navegação.
#+begin_src elisp :tangle "init.el"
(defun jclmntn/toggle-speedbar-window ()
  (interactive)
  (if (string-equal (buffer-name) " SPEEDBAR")
      (speedbar-window)
    (speedbar-get-focus)))
#+end_src
** elfeed
Meu leitor de feeds RSS de escolha. Também criei uma função para exportar dados desses feeds para bibtex.
#+begin_src elisp :tangle "init.el"
(defun jclmntn/elfeed-entry-to-bibtex ()
  "A simple function to export elfeed entry metadata into bibtex format, killing its result into the kill ring."
  (interactive)
  (let*
      ((entry (elfeed-search-selected :entry))
       (title (elfeed-entry-title entry))
       (link (elfeed-entry-link entry))
       (year (format-time-string "%Y" (seconds-to-time (elfeed-entry-date entry))))
       (authors-raw (elfeed-meta entry :authors))
       (first-author (plist-get (car authors-raw) :name))
       (first-author-last-name (car (last (split-string first-author))))
       (authors
        (if authors-raw
            (mapconcat (lambda (author) (plist-get author :name)) authors-raw ", ")
          "Unknown Authors"))
       (bibtex-entry (format
              "@misc{%s%s, author = {%s}, title = {%s}, year = {%s}, url = {%s}}"
              first-author-last-name year authors title year link)))
    (kill-new bibtex-entry)
    (message bibtex-entry)))
(use-package elfeed
  :custom ((elfeed-feeds '(("https://www.tandfonline.com/feed/rss/cjas20" journal stats)
                           ("https://hdsr.mitpress.mit.edu/rss.xml" blog data)
                           ("https://rss.sciencedirect.com/publication/science/01482963" journal business stats)
                           ("http://feeds.harvardbusiness.org/harvardbusiness/" blog business)
                           ("https://www.insurancejournal.com/rss/news" news insurance)
                           ("https://www.nexojornal.com.br/rss.xml" news brazil)
                           ("https://www.counting-stuff.com/rss" blog stats)
                           ("https://blog.miguelgrinberg.com/feed" blog python)
                           ("https://davidvujic.blogspot.com/feeds/posts/default" blog python agile)
                           ("https://grouplens.org/feed/" blog computing)
                           ("https://protesilaos.com/master.xml" blog philosophy emacs)))))
#+end_src
* Embelezamento do Emacs
Algumas configurações relacionadas ao próprio embelezamento do Emacs e derivados.
** Destaque de palavras-chave em código
Esse é um pacote desenvolvido pelo Tarsius, que é o atual mantenedor do =magit=. Ele não está disponível no melpa.
#+begin_src elisp :tangle "init.el"
  (use-package hl-todo
    :vc (:url "https://github.com/tarsius/hl-todo" :rev :newest)
    :hook ((prog-mode . hl-todo-mode)
           (yaml-mode . hl-todo-mode))
    :config
    (setq hl-todo-keyword-faces
           '(("TODO"   . "#FF0000")
             ("FIXME"  . "#FF0000"))))
#+end_src
** Tema, Fonte e Barra de Navegação
Aqui seguem os elementos visuais do próprio Emacs em si.
#+begin_src elisp :tangle "init.el"
(load-theme 'modus-operandi)

(set-face-attribute 'default nil :font "IosevkaTerm" :height 140)
(set-face-attribute 'fixed-pitch nil :font "IosevkaTerm" :height 140)
(set-face-attribute 'variable-pitch nil :font "IosevkaTerm" :height 140 :weight 'regular)

(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(menu-bar-mode -1)
(set-fringe-mode '(20 . 0))
#+end_src
** Ícones nerde em diferentes contextos
#+begin_src elisp :tangle "init.el"
(use-package nerd-icons
  :custom (nerd-icons-font-family "Symbols Nerd Font Mono"))

(use-package nerd-icons-dired
  :hook
  (dired-mode . nerd-icons-dired-mode))

(use-package nerd-icons-completion
  ;; :after vertico
  :config
  (nerd-icons-completion-mode)
  (with-eval-after-load 'marginalia
  (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup)))

(use-package nerd-icons-ibuffer
  :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src
** pulsar
#+begin_src elisp :tangle "init.el"
(use-package pulsar
  :bind
  ( :map global-map
    ("C-x l" . pulsar-pulse-line) ; overrides `count-lines-page'
    ("C-x L" . pulsar-highlight-permanently-dwim)) ; or use `pulsar-highlight-temporarily-dwim'
  :init
  (pulsar-global-mode 1)
  :config
  (setq pulsar-delay 0.055)
  (setq pulsar-iterations 5)
  (setq pulsar-face 'pulsar-green)
  (setq pulsar-region-face 'pulsar-yellow)
  (setq pulsar-highlight-face 'pulsar-magenta))
#+end_src
** doom-modeline
Uma modeline bonitinha. Eu gosto muito da =doom-modeline=, mas eu poderia criar a minha própria um dia.
#+begin_src elisp :tangle "init.el"
(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom
  (doom-modeline-vcs-max-length 30))
#+end_src
** racket-mode
#+begin_src elisp :tangle "init.el"
(use-package racket-mode
  :mode (("\\.scm\\'" . racket-mode))
  :config
  (add-to-list 'display-buffer-alist
               '(
                 "\\*Racket REPL"
                 (display-buffer-reuse-mode-window
                  display-buffer-below-selected)
                 (window-height . 10)
                 (dedicated . t))))
#+end_src
** just-mode
#+begin_src elisp :tangle "init.el"
(use-package just-mode)
#+end_src
** ox-pandoc
#+begin_src elisp :tangle "init.el"
(use-package ox-pandoc)
#+end_src
* Emulação de Terminal e Relacionados
Utilizo o =EAT= (emulate a terminal) como emulador de terminal, embora tenha considerado utilizar o =ghostel= cada vez mais.
#+begin_src elisp :tangle "init.el"
(use-package eat
  :config (eat-eshell-mode))
#+end_src
* Inteligência
Quando falo em inteligência, quero dizer incluir coisas que tornam o Emacs mais inteligente e aí várias coisas podem cair nesse critério.
** Minibuffer/Completions
No Emacs 31, eu criei a coragem de usar a solução nativa de emacs, abandonando o =vertico=. Copiei algumas coisas do que vi no [[https:protesilaos.com]]. Inclusive, sendo bem honesto, eu ainda não gosto de algumas coisas:
- Eu odeio o fato de que as sugestões aparecem acima do minibuffer e não embaixo, como no caso do vertico.
- Sinto falta daquele /cookie/: [nr da opção corrente/nr de opções disponíveis]
  - Inclusive, sobre esse último, eu acho que é bem possível ajustar isso. Depois tenho que ler o código com mais cautela.
- No org-mode, o completion buffer tem um problema bastante chato: quando aperto =<TAB>= para ele inserir uma sugestão de cabeçalho ou =<RET>=, ele não insere.
- O comportamento do salto do minibuffer para o buffer de completions é muito estranho. Se eu aperto =<TAB>= ele vai para o completion, mas a partir daí, eu não posso mais digitar.
  - Parece que com o =minibuffer-completion-auto-choose= a gente até consegue replicar algum comportamento do vertico, mas falta ter o mesmo comportamento com buffers do =consult=
  - Consegui traçar o problema em buffers do =consult-line=, outros buffers do consult funcionam como o esperado.
#+begin_src elisp :tangle "init.el"
;; Pensei em incluir isso, mas não dá certo.
;; (defun jclmntn/completion-ret-or-first ()
;;   "RET no minibuffer, imitando o vertico:
;; 1. Se houver um candidato selecionado no buffer de completions
;;    (por navegação com setas via `minibuffer-visible-completions'),
;;    confirma esse candidato.
;; 2. Senão, se o texto digitado já for uma opção válida, confirma
;;    como está.
;; 3. Senão, se houver candidatos disponíveis, pula para o primeiro
;;    e confirma.
;; 4. Senão, aceita o texto digitado como está (ex: nomes novos)."
;;   (interactive)
;;   (cond
;;    ((and (fboundp 'minibuffer-choose-completion-if-selected)
;;          (minibuffer-choose-completion-if-selected)))
;;    ((test-completion (minibuffer-contents)
;;                       minibuffer-completion-table
;;                       minibuffer-completion-predicate)
;;     (exit-minibuffer))
;;    ((completion-all-sorted-completions)
;;     (minibuffer-force-complete-and-exit))
;;    (t
;;     (exit-minibuffer))))

(defun prot-minibuffer-completions-tweak-style ()
  "Tweak the style of the Completions buffer."
  (setq-local mode-line-format nil)
  (setq-local cursor-in-non-selected-windows nil)
  (when (and completions-header-format
             (not (string-blank-p completions-header-format)))
    (setq-local display-line-numbers-offset -1))
  (display-line-numbers-mode 1))

(use-package minibuffer
  :ensure nil
  :bind
  (:map completion-list-mode-map
        ("RET" . choose-completion))
  ;;   :map minibuffer-local-completion-map
  ;;     ([remap minibuffer-complete-and-exit] . jclmntn/completion-ret-or-first)
  :custom
  ((completion-show-help nil)
   (completion-show-inline-help t)
   (completions-detailed t)
   (completions-format 'one-column)
   (completions-max-height 12)
   (completions-max-annotation-limit 30)
   (completions-sort 'historical)
   (completions-header-format (propertize "%s possible completions:\n" 'face 'shadow))
   (completions-group t)
   (completion-auto-help 'always)
   (completion-auto-select t)
   (completion-tab-width 1)
   (completion-eager-display t)
   (completion-eager-update t)
   (minibuffer-visible-completions 'up-down)
   (minibuffer-completion-auto-choose t))
  :config
  (define-key completion-in-region-mode-map (kbd "RET") #'choose-completion)
  (advice-add 'exit-minibuffer :around
              (lambda (orig-fn &rest args)
                (if (not (minibufferp))
                    (call-interactively #'choose-completion)
                  (apply orig-fn args)))))
#+end_src
** Ações contextuais de minibuffer
Para ações contextuais de minibuffer, eu utilizo o =embark=.
#+begin_src elisp :tangle "init.el"
(use-package embark
  :bind (
         ("C-." . embark-act)
         ("M-." . embark-dwim)
         ("C-h b" . embark-bindings))
  :custom
  ((prefix-help-command #'embark-prefix-help-command))
  )

(use-package embark-consult
  :after embark
  :hook (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

** Busca sem ordem
#+begin_src elisp :tangle "init.el"
(use-package orderless
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src


** Busca em geral
Aqui estou inserindo todas as coisas relacionadas ao =consult=.
Um dos problemas mais prementes é que as sugestões do completion buffer, relacionadas como o [[*Minibuffer]] também estão apresentando um problema desagradável, que eu comento em [[*Anotações]].

#+begin_src elisp :tangle "init.el"
(use-package consult
  :bind
  (("C-s" . consult-line)
   ("C-x b" . consult-buffer)))

;; Em algum momento considerei isso para sempre selecionar a primeira opção, mas isso acaba estragando tudo.
;; (:map consult-narrow-map
;;          ([remap exit-minibuffer] . minibuffer-force-complete-and-exit))

(use-package consult-imenu
  :after consult
  :ensure nil)

(use-package consult-notes
  :commands (consult-notes consult-notes-search-in-all-notes)
  :config
  (consult-notes-org-headings-mode)
  (consult-notes-denote-mode)
  (when (locate-library "denote")
    (consult-notes-denote-mode))
  :custom
  ((consult-notes-file-dir-sources '(("Denote" ?d "~/Repos/Notes/denote-notes/")))
   (consult-notes-denote-title-width 50)))
#+end_src
** Correções ortográficas
Precisa do =Enchant-2= instalado. Se eu estiver usando o =aspell= como dicionário, lembrar de instalar o =enchant2-aspell=.
O papel do enchant é encontrar qualquer tipo de dicionário encontrado na minha máquina.
Lembre-se que o =jinx-languages= precisa ter separação de idiomas com espaços numa única string.
#+begin_src elisp :tangle "init.el"
(use-package jinx
  :after embark
  :if (eq system-type 'gnu/linux)
  :hook (emacs-startup . global-jinx-mode)
  :bind (("M-$" . jinx-correct)
         ("C-M-$" . jinx-language))
  :custom
  (jinx-languages "pt_BR en_US")
  :config
  (setq ispell-alternate-dictionary (expand-file-name "pt_BR_words.txt" user-emacs-directory))
  (keymap-set jinx-repeat-map "RET" 'jinx-correct)
  (embark-define-overlay-target jinx category (eq %p 'jinx-overlay))
  (add-to-list 'embark-default-action-overrides '(jinx . jinx-correct))
  (add-to-list 'embark-target-finders 'embark-target-jinx-at-point)
  (add-to-list 'embark-keymap-alist '(jinx jinx-repeat-map embark-general-map))
  (add-to-list 'embark-repeat-actions #'jinx-next)
  (add-to-list 'embark-repeat-actions #'jinx-previous)
  (add-to-list 'embark-target-injection-hooks (list #'jinx-correct #'embark--ignore-target)))
#+end_src

Executar isso gera um dump de palavras para o autocomplete emportuguês brasileiro:
#+begin_src sh
aspell -d pt_BR dump master > ~/.emacs.d/pt_BR_words.txt
#+end_src

#+begin_src elisp :tangle "init.el"
(use-package ispell
  :custom
  (ispell-alternate-dictionary (expand-file-name "pt_BR_words.txt" user-emacs-directory)))
#+end_src

** Anotações
Para anotar coisas que aparecem no =Completions=, eu utilizo o =marginalia=. Essa opção =marginalia-align-offset -10= está aí porque quando não uso ela as colunas do buffer de completions ficam muito separadas, fazendo com que as linhas quebrem e o visual fique horrível.
#+begin_src elisp :tangle "init.el"
(use-package marginalia
  ;; :after vertico
  :init (marginalia-mode)
  :custom (marginalia-align-offset -10))
#+end_src
** Desenvolvimento de software
*** Agentes
**** ECA
#+begin_src elisp :tangle "init.el"
(use-package eca
  :vc (:url "https://github.com/editor-code-assistant/eca-emacs" :rev :newest))
#+end_src
*** Controle de Versionamento
Eu não uso tanto o =vc= do Emacs, costumo usar muito mais o =magit=. Perceba o uso do modo hl-todo para fazer marcações coloridas nos buffers do magit.
#+begin_src elisp :tangle "init.el" 
  (use-package magit
    :custom
    (magit-display-buffer-action #'magit-display-buffer-same-window-except-diff-v1))

  (with-eval-after-load 'magit
      (add-hook 'magit-log-wash-summary-hook
                #'hl-todo-search-and-highlight t)
      (add-hook 'magit-revision-wash-message-hook
                #'hl-todo-search-and-highlight t))

  ;; Não está funcionando atualmente, preciso entender o porquê.
  ;; Abri um PR no Forge.
  (use-package forge
    :after magit)

  (use-package magit-todos
    :after magit
    :config (magit-todos-mode 1))

  ;; Pra forçar a codificação do comando git.
  ;; Engraçado que isso tenha dado certo, significa que por alguma razão o git tem outra codificação mesmo no WSL.
  (setq-default process-coding-system-alist (cons '("git" . (utf-8 . utf-8)) process-coding-system-alist))
#+end_src

*** Expansões/Snippets
Eu tendo a utilizar o =yasnippet= para expansões.
#+begin_src elisp :tangle "init.el"
(use-package yasnippet
  :config
  (setq yas-snippet-dirs '("~/Repos/Notes/Snippets/"))
  (yas-global-mode 1))

#+end_src

*** Expansão de blocos de código
A princípio, eu estou usando o =hideshow= para fazer expansão de blocos de código. Fico pensando se no futuro há a necessidade de utilizar alguma outra alternativa.
#+begin_src elisp :tangle "init.el"
(use-package hideshow
  :ensure nil
  :hook (prog-mode . hs-minor-mode))
#+end_src

*** LSP
Ultimamente, eu tendo a preferir a solução nativa do Emacs, que é o =eglot=. Ele me atende bem, em especial se eu utilizar o [[https://github.com/joaotavora/rassumfrassum][rassumfrassum]] como multiplexer de diferentes servidores de linguagem. Hoje, tenho só configurações para o =python=. Primeiro, configuro uma função que cuida de gerenciar todos os servidores de linguagem, inclusive usando o =uv= como ferramenta:
#+begin_src elisp :tangle "init.el"
(defun jclmntn/rass-uvtool-command ()
      (let ((uv-tool-command '("uv" "tool" "run" "--from" "rassumfrassum" "rass"))
           (rass-separator '("--"))
           (ty-server-command '("ty" "server"))
           (ruff-server-command '("ruff" "server"))
           (pylsp-server-command '("pylsp")))
        (apply #'append 
               (list
                uv-tool-command
                rass-separator
                ty-server-command
                rass-separator
                ruff-server-command
                rass-separator
                pylsp-server-command))))
#+end_src

Preciso integrar o =yasnippets= ao =eglot=, e para isso eu uso o =cape=, que ajuda a criar uma =completion-at-point-function='s. Tudo isso foi tirado desse [[https://github.com/minad/corfu/wiki#making-a-cape-super-capf-for-eglot][link]], provavelmente.
#+begin_src elisp :tangle "init.el"
(use-package cape)
(use-package yasnippet-capf :after cape)

(defun jclmntn/eglot-capf-with-yasnippet ()
  (setq-local completion-at-point-functions
              (list 
	       (cape-capf-super
		#'eglot-completion-at-point
		#'yasnippet-capf))))
#+end_src

Finalmente, entra a configuração do =eglot=: a última função entra como /hook/, a primeira função vira parte dos programas de servidores do =eglot=.
#+begin_src elisp :tangle "init.el"
(use-package eglot
  :hook (eglot-managed-mode . jclmntn/eglot-capf-with-yasnippet)
  :config
  (add-to-list 'eglot-server-programs '(python-mode . jclmntn/rass-uvtool-command))
  (add-to-list 'eglot-server-programs '(python-ts-mode . jclmntn/rass-uvtool-command)))
#+end_src

E aí vem a firulagem de ter um boxes com informações do =eglot=:
#+begin_src elisp :tangle "init.el"
(use-package eldoc-box
  :hook (eglot-managed-mode . eldoc-box-hover-at-point-mode))
#+end_src

*** Parênteses coloridos
=((((Fundamental))))=.
#+begin_src elisp :tangle "init.el"
(use-package rainbow-delimiters
             :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

*** Python
Algumas configurações específicas para python.
#+begin_src elisp :tangle "init.el"
(defun jclmntn/python-dynamic-shell-args (&rest _args)
  "Dynamically set python shell args based on pyproject.toml"
  (let ((pyproject-file (locate-dominating-file default-directory "pyproject.toml")))
    (when pyproject-file
      (let ((args (with-temp-buffer
                    (insert-file-contents (expand-file-name "pyproject.toml" pyproject-file))
                    (goto-char (point-min))
                    (cond
                     ((re-search-forward "kedro" nil t) "run kedro ipython --simple-prompt -i")
                     ((progn (goto-char (point-min)) (re-search-forward "ipython" nil t)) "run ipython")
                     (t "run python -i")))))
        (setq-local python-shell-interpreter-args args)
        (message "Python args set to: %s" args)))))

(use-package python
  :mode (("\\.py\\'" . python-ts-mode))
  :hook ((python-ts-mode . display-fill-column-indicator-mode)
         (python-ts-mode . jclmntn/python-dynamic-shell-args)
         (python-ts-mode . jclmntn/python-dynamic-shell-args))
  :custom ((python-shell-interpreter "uv")
           (python-shell-interpreter-args "run python -i")
           (python-indent-offset 4)
           (python-indent-def-block-scale 1)
           (python-shell-prompt-detect-enabled nil))
  :config
  (advice-add 'run-python :before #'jclmntn/python-dynamic-shell-args))

#+end_src

Projetos =uv= criam um =pyproject.toml= em suas raízes. Isso faz com que o project do Emacs os reconheça. Claro que isso é irrelevante quando você torna o projeto um repositório, mas pode ser útil em monorepositórios.
#+begin_src elisp :tangle "init.el"
(use-package project
  :custom
  ((project-mode-line t)
   (project-vc-extra-root-markers '("pyproject.toml"))))
#+end_src

*** Sugestões/Autocomplete
Abandonei o =corfu= a partir do emacs 31 por uma solução menos intrusiva.
#+begin_src elisp :tangle "init.el"
(pcase emacs-version
  ("31.1"
   (use-package completion-preview
     :ensure nil
     :demand t
     :custom (completion-preview-minimum-symbol-length 1)
     :bind
     ( :map completion-preview-active-mode-map
       ("M-i" . completion-preview-insert-word)
       ("M-n" . completion-preview-next-candidate)
       ("M-p" . completion-preview-prev-candidate)
       ("M-<return>" . completion-preview-insert)
       ;; Mostra candidatos
       ("<tab>" . completion-preview-complete))
     :config (global-completion-preview-mode 1)))
  (_
   (use-package corfu
     :custom
     (corfu-cycle t)
     (corfu-auto-prefix 1)
     (corfu-auto t)
     :init
     (global-corfu-mode)
     (advice-add 'python-shell-completion-at-point :around
                 (lambda (fun &optional arg)
                   (cape-wrap-noninterruptible (lambda () (funcall fun arg))))))))
#+end_src

*** SQL
#+begin_src elisp :tangle "init.el"
(defun jclmntn/ejc-maybe-add-limit (args)
  "Inject LIMIT 200 into SELECT queries that do not already specify a limit."
  (let* ((sql (car args))
         (upper (when sql (upcase (string-trim sql)))))
    (if (and upper
             (or (string-match-p "\\`SELECT\\b" upper)
                 (string-match-p "\\`WITH\\b" upper))
             (not (string-match-p "\\bLIMIT\\b" upper)))
        (cons (concat (string-trim-right sql) "\nLIMIT 200") (cdr args))
      args)))

(defun jclmntn/ejc-sql-connected-hook ()
  (ejc-set-fetch-size 99)         ; Limit for the number of records to output.
  (ejc-set-max-rows 99)           ; Limit for the number of records in ResultSet.
  (ejc-set-show-too-many-rows-message t) ; Set output 'Too many rows' message.
  (ejc-set-column-width-limit nil) ; Limit for outputing the number of chars per column.
  (ejc-set-use-unicode t)         ; Use unicode symbols for grid borders.
  )

(use-package ejc-sql
  :hook (ejc-sql-connected . jclmntn/ejc-sql-connected-hook)
  :custom
  (ejc-nrepl-timeout nil)
  (ejc-show-result-bottom t)
  :config
  (setq nrepl-sync-request-timeout nil)
  (require 'ejc-completion-common)
  (advice-add 'ejc-eval-user-sql :filter-args #'jclmntn/ejc-maybe-add-limit)
  (ejc-create-connection
   "BigQuery"
   :dependencies [[com.simba.googlebigquery/googlebigquery-jdbc42 "1.6.3.1004"]
                  [com.google.cloud/google-cloud-bigquerystorage "3.9.3"]
                  [com.google.apis/google-api-services-bigquery "v2-rev20240919-2.0.0"]
                  [com.google.auth/google-auth-library-oauth2-http "1.28.0"]]
   :classname "com.simba.googlebigquery.jdbc.Driver"
   :connection-uri (concat "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443"
                           ";ProjectId=azos-data-analytics"
                           ";OAuthType=0"
                           ";OAuthServiceAcctEmail=azos-feature-store@azos-data-analytics.iam.gserviceaccount.com"
                           ";OAuthPvtKeyPath=" (expand-file-name "~/.config/gcloud/feature-store.json")))

    (let* ((auth (car (auth-source-search :host "postgres-dis")))
         (user (plist-get auth :user))
         (subname (plist-get auth :subname))
         (password (let ((secret (plist-get auth :secret)))
                     (if (functionp secret) (funcall secret) secret))))
    (ejc-create-connection
     "PostgreSQLDis"
     :dependencies [[org.postgresql/postgresql "42.7.3"]]
     :classpath (concat "~/.m2/repository/org.postgresql/postgresql/42.7.3/"
                        "postgresql-42.7.3.jar")
     :subprotocol "postgresql"
     :subname subname
     :user user
     :password password)))
#+end_src

* ORGanização
Tudo sobre org-mode fica aqui!
** Funções customizadas
*** Aspectos visuais
Essa primeira função organiza alguns aspectos visuais de /buffers/ do =org-mode=. Perceba que aqui eu já tenho uma dependência com o =cape=, =yasnippets= e =yasnippets-capf=.
#+begin_src elisp :tangle "init.el"
(defun jclmntn/org-mode-setup ()
  (org-indent-mode)
  (variable-pitch-mode 1)
  (visual-line-mode)
  (add-hook 'completion-at-point-functions
            (cape-capf-super #'yasnippet-capf)
            nil t))
#+end_src

Essa função permite que os resultados do =org-babel= tenham formatação colorida quando for possível.
#+begin_src elisp :tangle "init.el"
(defun jclmntn/babel-ansi ()
  (when-let ((beg (org-babel-where-is-src-block-result nil nil)))
    (save-excursion
      (goto-char beg)
      (when (looking-at org-babel-result-regexp)
        (let ((end (org-babel-result-end))
              (ansi-color-context-region nil))
          (ansi-color-apply-on-region beg end))))))
#+end_src

*** Capturas
Aqui temos uma função que contém todas as capturas do org-mode.
#+begin_src elisp :tangle "init.el"
(defun jclmntn/org-capture-templates ()
  "Return custom org-capture templates list."
  '(("i" "Idea" entry
     (file+olp "~/Repos/Notes/Tasks.org" "Caixa de Entrada") 
     "* IDEA %?\n%U\n %a\n %i"
     :empty-lines 1)
    ("l" "Log" entry
     (file+olp denote-journal-path-to-new-or-existing-entry "Logs")
     "* %U %?\n%i\n%a"
     :kill-buffer t
     :empty-lines 1)
    ("p" "Project Task" entry
     (file+headline org-default-notes-file "Inbox")
     "* IDEA %?\n Created: %U\n Link: %a")))
#+end_src
** Gestão de conhecimento
Meu pacote de escolha para gestão do conhecimento é o =denote=.
Vez ou outra eu crio notas de sequência e notas de diário, mas é raro.
#+begin_src elisp :tangle "init.el"
(use-package denote
  :hook (dired-mode . denote-dired-mode)
  :custom ((denote-templates '((journal . "* Logs"))))
  :config
  (setq denote-directory (expand-file-name "~/Repos/Notes/denote-notes"))
  (denote-rename-buffer-mode 1))

(use-package denote-sequence)

(use-package denote-journal
  :custom ((denote-journal-directory
            (expand-file-name "journal" denote-directory))
           (denote-journal-title-format 'day-date-month-year)))
#+end_src
** Gestão de referências bibliográficas
O motor de referências bibliográficas que cuida da relação bibtex <-> =org-mode= é o =citar=. O =citar= só funciona corretamente depois que o =org-mode= é ativado. Parece que o =citar-org= não é automaticamente solicitado pelo =citar=. Só recebo a partir do primeiro caractere do =[cite:@]=, com comportamento configurável em =completion-preview=.
#+begin_src elisp :tangle "init.el"
(use-package citar
  :after org
  :demand t
  :custom
  (citar-open-always-create-notes nil)
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  :config
  (require 'citar-org)
  (setq citar-bibliography (file-expand-wildcards "~/Repos/Notes/bib/*.bib"))
  :bind (:map org-mode-map ("C-c b" . #'org-cite-insert))
  :hook (org-mode . (lambda ()
                      (require 'citar-capf)
                      (citar-capf-setup))))

(use-package citar-embark
  :after citar embark
  :no-require
  :config (citar-embark-mode)) 

(use-package citar-denote
  :demand t ;; Ensure minor mode loads
  :after (:any citar denote)
  :custom
  ;; Package defaults
  (citar-denote-file-type 'org)
  (citar-denote-keyword "bib")
  (citar-denote-subdir "bib")
  (citar-denote-template nil)
  (citar-denote-title-format "author-year-title")
  (citar-denote-title-format-andstr "and")
  (citar-denote-title-format-authors 1)
  :init
  (citar-denote-mode))
#+end_src

Para gerenciar arquivos bibtex, eu utilizo o =ebib=.
#+begin_src elisp :tangle "init.el"
  (use-package ebib
    :custom (ebib-default-directory "~/Repos/Notes/bib/"))

  (use-package ebib-biblio
    :ensure nil
    :after (ebib biblio)
    :bind (:map ebib-index-mode-map
                ("B" . ebib-biblio-import-doi)
                :map biblio-selection-mode-map
                ("e" . ebib-biblio-selection-import)))
#+end_src

Para obter referências bibliográficas de diferentes fontes, eu utilizo o =biblio=.
#+begin_src elisp :tangle "init.el"
(use-package biblio)

(use-package biblio-openlibrary
  :vc (:url "https://github.com/fabcontigiani/biblio-openlibrary" :branch "master")
  :after biblio
  :demand t)
#+end_src

** A configuração do org-mode em si                                    :WSL:
Eu precisei fazer um hardcoding do valor de uma função devido a problemas quando trabalho com o WSL.
De vez em quando eu crio objetos no plantuml, então ele está pré-configurado.
#+begin_src elisp :tangle "init.el" 
(use-package org
  :hook
  (org-mode . jclmntn/org-mode-setup)
  (org-babel-after-execute . jclmntn/babel-ansi)
  :custom 
  ((org-todo-keywords
    '((sequence "TODO(t!)" "PROJ(j)" "NEXT(n)" "IDEA(i)" "|" "DONE(d!)" "KILL(k!)")))
   (org-agenda-files '("~/Repos/Notes/Tasks.org"))
   (org-log-into-drawer t)
   (org-log-done 'time)
   (org-agenda-window-setup 'only-window)
   (org-agenda-restore-windows-after-quit t)
   (org-src-window-setup 'plain)
   (org-src-preserve-indentation t)
   (org-confirm-babel-evaluate nil)
   (org-plantuml-jar-path "~/.config/plantuml/plantuml-mit-1.2025.9.jar")
   (org-latex-src-block-backend 'engraved)
   (org-latex-pdf-process
    '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
      "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
      "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
   (org-cite-csl-link-cites nil)
   (org-cite-csl-nocitelinks-backends '(ascii md gfm))
   (org-refile-targets '(("~/Repos/Notes/Tasks.org" :maxlevel . 3)))
   (org-imenu-depth 3))
  :config
  (setq org-capture-templates (jclmntn/org-capture-templates))
  (add-to-list 'org-src-lang-modes '("planuml" . plantuml))
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(
     (emacs-lisp . t)
     (python . t)
     (plantuml . t)
     (eshell . t)))
  (defun org--get-display-dpi ()
    "Hardcode display DPI to bypass PGTK/Wayland arithmetic overflow bug."
    200.0))
#+end_src
** Transclusões
#+begin_src elisp :tangle "init.el"
(use-package org-transclusion :after org)
#+end_src
** Embelezamento 
Uma carinha mais bela para buffers do org-mode
#+begin_src elisp :tangle "init.el"
(use-package org-modern
  :config
  (global-org-modern-mode))
#+end_src
** Hábitos
Preciso disso ativo para garantir que os hábitos funcionam.
#+begin_src elisp :tangle "init.el"
(require 'org-habit)
#+end_src

* Finanças pessoais
** Funções utilitárias
Criei algumas funções utilitárias para =hledger-mode=.
Talvez não seja necessário manter a função de imenu porque eu descobri recentemente a existência de um /parser/ de tressitter para =hledger=.
#+begin_src elisp :tangle "init.el"
(defun jclmntn/short-hledger-amount ()
  "Target an amount at point of the form hledger-amount-value-regex"
  (save-excursion
    (let* ((line-start (line-beginning-position))
           (line-end (line-end-position))
           (str (buffer-substring-no-properties line-start line-end))
           (match (string-match (concat hledger-currency-string " ?" hledger-amount-value-regex) str))
           (buffer-match-start (+ line-start (match-beginning 0)))
           (buffer-match-end (+ line-start (match-end 0))))
      (save-match-data
        (when (and (derived-mode-p 'hledger-mode) match)
          `(hledger-amount
            ,(format "%s" (match-string 0 str))
            ,buffer-match-start . ,buffer-match-end))))))

(defun hledger-completion-accounts ()
  (when-let ((bounds (and (boundp 'hledger-accounts-cache)
                          (bounds-of-thing-at-point 'symbol))))
    (list (car bounds) (point) hledger-accounts-cache)))

(defun jclmntn/hledger-imenu ()
    (setq-local imenu-create-index-function #'imenu-default-create-index-function)
    (setq-local imenu-generic-expression '(("Dates" "\\([0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\)" 1))))

(defun jclmntn/hledger-align-currency ()
  (save-excursion
    (save-restriction
      (widen)
      (align-regexp (point-min) (point-max) "\\(\\s-*\\)R\\$" 1 1 nil))))
#+end_src
** Hledger
#+begin_src elisp :tangle "init.el"
(use-package hledger-mode
  :mode "\\.journal\\'"
  :custom
  ((hledger-jfile "~/Repos/hlfinances/2026.journal") ;; Sempre atualizar para o mais recente.
   (hledger-currency-string " R$")
   (hledger-year-of-birth 1995)
   (hledger-reporting-day 1)
   (hledger-ratios-liquid-asset-accounts "assets:bank assets:wallet assets:caixinha")
   (hledger-ratios-essential-expense-accounts "expenses:food expenses:groceries expenses:energy expenses:water expenses:streaming expenses:internet expenses:cellphone expenses:telephone"))
  :hook
  ((hledger-mode . (lambda ()
                     (add-hook 'completion-at-point-functions 'hledger-completion-accounts)))
   (hledger-mode . jclmntn/hledger-imenu)
   (hledger-mode . (lambda () (add-hook 'before-save-hook #'jclmntn/hledger-align-currency))))
  :config
  (with-eval-after-load 'embark
    (add-to-list 'embark-target-finders 'jclmntn/short-hledger-amount)
    (add-to-list 'embark-keymap-alist '(hledger-amount hledger-amount-keymap))
  (defvar-keymap hledger-amount-keymap
    :doc "Keymap for 'hledger-amount'"
    :parent embark-general-map
    "RET" #'hledger-edit-amount)))
#+end_src

# Local Variables:
# eval: (add-hook 'after-save-hook #'org-babel-tangle nil t)
# End:
